[build]
  command = "npm run maybe-build"
  publish = "public"
  functions = "functions"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  CLOUDINARY_CLOUD_NAME = "Your Cloudinary Cloud Name (e.g. @jlengstorf)"
  CLOUDINARY_IMAGE_PUBLIC_ID = "Public ID for your social image template (e.g. v1591839476/social/og.png)"

[dev]
  command = "npm run dev"
